/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'timbo' at '10/23/15 11:03 AM' with Gradle 2.2.1
 *
 * @author timbo, @date 10/23/15 11:03 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
